### ISSUE TITLE
Suggestion: interpret CamelCasing as implicit wildcard

### ISSUE THREAD

**Issue by runeflobakk** [mystilleef/eclipse4-fastopen#3]
Example:
When searching for "MessSen" in the regular Open Resource-dialog (Navigate -> Open Resource), I get a hit on MessageSender.java, but FastOpen yields no hits.

The suggestiong is to recognize the use of camelcasing, and treat each part of the camelcased search term as sort of "Mess*Sen*" and give hits on every file which contains "Mess", followed by any characters, followed by "Sen".

**Comment by mystilleef** [comment]
Okay, I pushed an update to the testing updatesite. If you do a "Check Update" the new version should appear with this feature. Test to see if this is the behavior you want.

**Comment by runeflobakk** [comment]
Works perfectly! Thank you! :smiley:
